server:
  port: 8080

spring:
  application:
    name: frontend # 指定应用名称，用于服务注册时候指定服务名
  profiles:
    active: prod
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: prod # 会注册到对应的服务的命名空间ID，替换为实际的ID
        group: DEV_GROUP # 配置分组
      config:
        import-check:
          enabled: false
# 配置okhttp-feign:看FeignAutoCongiguration.OkHttpFeignConfiguration，这个配置类是用于使用okhttp接管feign的配置类，这个配置类生效的条件之一就是这个配置项
    openfeign:
      okhttp:
        enabled: true
