server:
  port: 9090

spring:
  application:
    name: frontend # 指定应用名称，用于服务注册时候指定服务名
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public # 会注册到对应的服务的命名空间ID，替换为实际的ID
        username: nacos # 开启鉴权，首次登陆nacos控制台的时候会设置管理员密码
        password: nacos1234
        group: DEV_GROUP # 配置分组 需要与关联的微服务能在同一个gourp之中
      config:
        import-check:
          enabled: false
    # 配置okhttp-feign:看FeignAutoCongiguration.OkHttpFeignConfiguration，这个配置类是用于使用okhttp接管feign的配置类，这个配置类生效的条件之一就是这个配置项
    openfeign:
      okhttp:
        enabled: true
