apiVersion: v1
kind: Service
metadata:
  name: my-service
  # annotations:
  #   service.kubernetes.io/topology-mode: Auto
spec:
  trafficDistribution: PreferClose
  selector:
    app.kubernetes.io/appname: nginx-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-1
  labels:
    app.kubernetes.io/appname: nginx-app
spec:
  containers:
    - name: nginx
      image: goose-good/nginx:1.27.3
      ports:
        - containerPort: 80
          name: http-web-svc
      command: ["/bin/sh", "-c"]
      args:
        - |
          sudo cat <<EOF > /usr/share/nginx/html/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>新首页1</title>
            </head>
            <body>
              <h1>通过 cat 命令写入的内容1</h1>
            </body>
          </html>
          EOF

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-2
  labels:
    app.kubernetes.io/appname: nginx-app
spec:
  containers:
    - name: nginx
      image: goose-good/nginx:1.27.3
      ports:
        - containerPort: 80
          name: http-web-svc
      command: ["/bin/sh", "-c"]
      args:
        - |
          sudo cat <<EOF > /usr/share/nginx/html/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>新首页2</title>
            </head>
            <body>
              <h1>通过 cat 命令写入的内容2</h1>
            </body>
          </html>
          EOF