package org.talk.is.cheap.project.free.flow.scheduler.cluster.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.scheduler.cluster.domain.pojo.ClusterNodeRegistryLog;
import org.talk.is.cheap.project.free.flow.scheduler.cluster.domain.query.example.ClusterNodeRegistryLogExample;

public interface ClusterNodeRegistryLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    long countByExample(ClusterNodeRegistryLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    int deleteByExample(ClusterNodeRegistryLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    int insertSelective(ClusterNodeRegistryLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    List<ClusterNodeRegistryLog> selectByExampleWithRowbounds(ClusterNodeRegistryLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    List<ClusterNodeRegistryLog> selectByExample(ClusterNodeRegistryLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    int updateByExampleSelective(@Param("record") ClusterNodeRegistryLog record, @Param("example") ClusterNodeRegistryLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Sat Aug 02 22:57:03 CST 2025
     */
    int insertBatch(Collection<ClusterNodeRegistryLog> records);
}