apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  # namespace: xxx # 可以指定这个LimitRange应用在哪个命名空间
spec:
  limits:
  - default: # 此处定义默认限制值
      cpu: 500m
    defaultRequest: # 此处定义默认请求值
      cpu: 500m
    max: # max 和 min 定义限制范围
      cpu: "1"
    min:
      cpu: 100m
    type: Container
