package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   序列表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table seq_generator
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class SeqGenerator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   序列名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.seq_name
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private String seqName;

    /**
     * Database Column Remarks:
     *   下一段的起始id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.next
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private String next;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.revision
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seq_generator.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String SEQ_NAME = "seq_name";

    /**
    used in order-by
    */
    public static final String NEXT = "next";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.id
     *
     * @return the value of seq_generator.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.id
     *
     * @param id the value for seq_generator.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.seq_name
     *
     * @return the value of seq_generator.seq_name
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withSeqName(String seqName) {
        this.setSeqName(seqName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.seq_name
     *
     * @param seqName the value for seq_generator.seq_name
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.next
     *
     * @return the value of seq_generator.next
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public String getNext() {
        return next;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withNext(String next) {
        this.setNext(next);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.next
     *
     * @param next the value for seq_generator.next
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setNext(String next) {
        this.next = next;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.revision
     *
     * @return the value of seq_generator.revision
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.revision
     *
     * @param revision the value for seq_generator.revision
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.create_time
     *
     * @return the value of seq_generator.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.create_time
     *
     * @param createTime the value for seq_generator.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seq_generator.update_time
     *
     * @return the value of seq_generator.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public SeqGenerator withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seq_generator.update_time
     *
     * @param updateTime the value for seq_generator.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seqName=").append(seqName);
        sb.append(", next=").append(next);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeqGenerator other = (SeqGenerator) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSeqName() == null ? other.getSeqName() == null : this.getSeqName().equals(other.getSeqName()))
            && (this.getNext() == null ? other.getNext() == null : this.getNext().equals(other.getNext()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSeqName() == null) ? 0 : getSeqName().hashCode());
        result = prime * result + ((getNext() == null) ? 0 : getNext().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}