package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   阶段启动表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table stage_startup
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class StageStartup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   任务启动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.task_startup_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Long taskStartupId;

    /**
     * Database Column Remarks:
     *   阶段id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.stage_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Long stageId;

    /**
     * Database Column Remarks:
     *   此次启动的状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.status
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   启动参数，存储于es中，考虑到es的id不一定为数字，因此设定为字符串类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.startup_param_es_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private String startupParamEsId;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.revision
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.create_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_startup.update_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String TASK_STARTUP_ID = "task_startup_id";

    /**
    used in order-by
    */
    public static final String STAGE_ID = "stage_id";

    /**
    used in order-by
    */
    public static final String STATUS = "status";

    /**
    used in order-by
    */
    public static final String STARTUP_PARAM_ES_ID = "startup_param_es_id";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.id
     *
     * @return the value of stage_startup.id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.id
     *
     * @param id the value for stage_startup.id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.task_startup_id
     *
     * @return the value of stage_startup.task_startup_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Long getTaskStartupId() {
        return taskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withTaskStartupId(Long taskStartupId) {
        this.setTaskStartupId(taskStartupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.task_startup_id
     *
     * @param taskStartupId the value for stage_startup.task_startup_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setTaskStartupId(Long taskStartupId) {
        this.taskStartupId = taskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.stage_id
     *
     * @return the value of stage_startup.stage_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Long getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withStageId(Long stageId) {
        this.setStageId(stageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.stage_id
     *
     * @param stageId the value for stage_startup.stage_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setStageId(Long stageId) {
        this.stageId = stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.status
     *
     * @return the value of stage_startup.status
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.status
     *
     * @param status the value for stage_startup.status
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.startup_param_es_id
     *
     * @return the value of stage_startup.startup_param_es_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public String getStartupParamEsId() {
        return startupParamEsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withStartupParamEsId(String startupParamEsId) {
        this.setStartupParamEsId(startupParamEsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.startup_param_es_id
     *
     * @param startupParamEsId the value for stage_startup.startup_param_es_id
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setStartupParamEsId(String startupParamEsId) {
        this.startupParamEsId = startupParamEsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.revision
     *
     * @return the value of stage_startup.revision
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.revision
     *
     * @param revision the value for stage_startup.revision
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.create_time
     *
     * @return the value of stage_startup.create_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.create_time
     *
     * @param createTime the value for stage_startup.create_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_startup.update_time
     *
     * @return the value of stage_startup.update_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public StageStartup withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_startup.update_time
     *
     * @param updateTime the value for stage_startup.update_time
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskStartupId=").append(taskStartupId);
        sb.append(", stageId=").append(stageId);
        sb.append(", status=").append(status);
        sb.append(", startupParamEsId=").append(startupParamEsId);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StageStartup other = (StageStartup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskStartupId() == null ? other.getTaskStartupId() == null : this.getTaskStartupId().equals(other.getTaskStartupId()))
            && (this.getStageId() == null ? other.getStageId() == null : this.getStageId().equals(other.getStageId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getStartupParamEsId() == null ? other.getStartupParamEsId() == null : this.getStartupParamEsId().equals(other.getStartupParamEsId()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskStartupId() == null) ? 0 : getTaskStartupId().hashCode());
        result = prime * result + ((getStageId() == null) ? 0 : getStageId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getStartupParamEsId() == null) ? 0 : getStartupParamEsId().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}