
server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultServer: http://${eureka.instance.hostname}:${server.port}/eureka/