apiVersion: v1
kind: Pod
metadata:
  name: sa-token-test
spec:
  containers:
  - name: container-test
    image: goose-good/busybox:1.37.0
    command: 
    # ["sleep", "3600"]
      - sh
      - -c
      - |
        echo "The app is running!" 
        ls -l /service-account && echo ""
        cat /service-account/token && echo ""
    volumeMounts:
    - name: token-vol
      mountPath: "/service-account"
      readOnly: true
  serviceAccountName: default
  volumes:
  - name: token-vol
    projected:
      sources:
      - serviceAccountToken:
          audience: api
          expirationSeconds: 3600
          path: token
