apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque  # 通用类型，可存储任意键值对
data:
  username: YWRtaW4=  # base64编码后的"admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque  # 通用类型，可存储任意键值对
data:
  password: c3VwZXJzZWNyZXQ=  # base64编码后的"supersecret"
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: container-test
    image: goose-good/busybox:1.37.0
    command: 
    # ["sleep", "3600"]
      - sh
      - -c
      - |
        echo "The app is running!" 
        id 
        ls -l /projected-volume/my-group/ 
        cat /projected-volume/my-group/my-username
        echo "" 
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      # readOnly: true
  volumes:
  - name: all-in-one
    projected:
      defaultMode: 0600  # 未单独指定时的默认权限
      sources:
      - secret:
          name: mysecret
          items:
            - key: username
              path: my-group/my-username
      - secret:
          name: mysecret2
          items:
            - key: password
              path: my-group/my-password
              # 这个需要是四位数字，如果写的是三位会出现奇怪的结果
              mode: 0555
