# 创建一个secret卷，来自豆包
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque  # 通用类型，可存储任意键值对
data:
  username: YWRtaW4=  # base64编码后的"admin"
  password: c3VwZXJzZWNyZXQ=  # base64编码后的"supersecret"
---
# 创建一个configMap卷
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: myconfigmap
data:
  config: balalbalal232132
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  labels: 
    env: dev
spec:
  containers:
  - name: container-test
    image: goose-good/busybox:1.37.0
    command: 
    # ["sleep", "3600"]
      - sh
      - -c
      - |
        echo "The app is running!" 
        ls -l /projected-volume 
        cat /projected-volume/my-group/my-username
        echo "" 
        cat /projected-volume/my-group/my-password 
        echo "" 
        cat /projected-volume/cpu_limit 
        echo "" 
        cat /projected-volume/labels 
        echo "" 
        cat /projected-volume/my-group/my-config 
        echo "" 
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      # 一个secret卷，上方定义的secret
      - secret:
          name: my-secret
          items:
            - key: username
              path: my-group/my-username
            - key: password
              path: my-group/my-password
      # downwardAPI可以获取k8s内部对象的一些属性，这个例子里就是取
      # 1. pod的label
      # 2. 容器container-test的cpu-limit
      - downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "cpu_limit"
              resourceFieldRef:
                containerName: container-test
                resource: limits.cpu
      - configMap:
          name: myconfigmap
          items:
            - key: config
              path: my-group/my-config
