server:
  port: 8082

  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  web:
    resources:
      static-locations:
#        默认静态资源在classpath:/static/
#        此路径表示在类路径下的 static 目录中查找静态资源。你需要在 src/main/resources 目录下创建 static 目录，并将静态资源放置其中。
        - classpath:/my-static
#       该路径表示在文件系统的指定目录中查找静态资源。你可以将静态资源存放在任意外部目录，然后使用绝对路径进行指定。
        - file:/path/to/external/static/resources/



  servlet:
    multipart:
      max-file-size: 10MB # 设置文件上传的最大大小
      max-request-size: 10MB
logging:
  level:
    root: info
