apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  # 每分钟执行一次
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: goose-good/busybox:1.37.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
