apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: log-config
data:
  log_level: INFO

binaryData:
  binary: balalbalal232132
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: goose-good/busybox:1.37.0
      command: 
        - sh
        - -c
        - | 
          echo "The app is running!" && 
          ls -l /etc/config &&
          cat /etc/config/log_level.conf && echo ""
          cat /etc/config/binary.conf && echo ""
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level.conf
          - key: binary
            path: binary.conf