package codegen.test.dao;

import codegen.test.dao.example.StudentExample;
import codegen.test.pojo.mbg.Student;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    List<Student> selectByExampleDeepPagingByIdSubQuery(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    int insertBatch(Collection<Student> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Sep 08 23:38:32 CST 2025
     */
    int insertBatchSelective(@Param("records") Collection<Student> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}