apiVersion: v1
kind: Pod
metadata:
  name: pod-in-m02
  labels:
    key-1: value-1
spec:
  nodeName: minikube-m02 # 调度 Pod 到特定的节点
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.10
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-in-m03
  labels:
    key-1: value-1
    key-2: value-2
spec:
  nodeName: minikube-m03 # 调度 Pod 到特定的节点
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.10
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: key-1
            operator: In
            values:
            - value-1
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: key-2
              operator: In
              values:
              - value-2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.10
