driverClassName=com.mysql.cj.jdbc.Driver
# https://www.qianwen.com/share/chat/148f7c55d6304e41b623560cf72c442e
url=jdbc:mysql://localhost:3306/free_flow?characterEncoding=utf8&serverTimezone=Asia/Shanghai
username=root
password=root