apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
#  job-with工作队列，不需要设置completions
  parallelism: 6
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pi
        image: python:3.7-alpine
        command:          
        - python3
        - -c
        - |
          import os, sys, random
          print("Hello world")
          if random.randint(0,2) % 2 == 0:
            sys.exit(1)
  # Job 里的 Pod 失败后，Kubernetes 最多允许重新创建多少次 Pod，超过这个次数，Job 标记为失败（Failed）。          
  backoffLimit: 4

