apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  # value-2的base64编码
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: goose-good/busybox:1.37.0
      command:
        - sh
        - -c
        - |
          ls -l  /etc/secret-volume
          ls -al /etc/secret-volume
          cat /etc/secret-volume/.secret-file
          echo ""
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"