apiVersion: v1
kind: Secret

metadata:
  name: db-secret

# 普通键值型 Secret，没有特殊含义。除此之外还有 kubernetes.io/basic-auth、kubernetes.io/ssh-auth、kubernetes.io/tls等类型的 Secret。但是这些类型的 Secret 也只是为了方便使用、语义更加明确而已，实际上它们的本质都是普通键值型 Secret。
type: Opaque

data:
# base64编码后的用户名和密码admin
  username: YWRtaW4=
  # 123456
  password: MTIzNDU2
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: app
    image: nginx:1.27.3
    # 把名为 db-secret 的 Secret 投影成一个 volume。
    volumeMounts:
    - name: db-secret-volume
      mountPath: /etc/db-secret
    # 通过环境变量挂载
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
  volumes:
  - name: db-secret-volume
    secret:
      secretName: db-secret