---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: api-reader
  namespace: default
---

# 测试是要先创建一个ServiceAccount，然后创建一个Secret，Secret的类型是kubernetes.io/service-account-token，Secret的名称和ServiceAccount的名称一致，Secret会自动生成三个字段：ca.crt、namespace、token。
apiVersion: v1
kind: Secret

metadata:
  name: api-reader-token

  annotations:
    kubernetes.io/service-account.name: "api-reader"

type: kubernetes.io/service-account-token
data:
# 创建后会自动生成三个字段
#   ca.crt: xxx
# namespace: xxx
# token: eyJhbGciOiJSUzI1Ni...
  extra: YmFyCg==

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: pod-reader

rules:
- apiGroups:
  - ""

  resources:
  - pods

  verbs:
  - get
  - list
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: pod-reader-binding

subjects:

- kind: ServiceAccount
  name: api-reader
  namespace: default


roleRef:

  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Pod

metadata:
  name: api-client


spec:

  containers:

  - name: client

    image: nginx:1.27.3


    volumeMounts:
    - name: sa-token
      mountPath: /var/run/secrets/my-token


  volumes:

  - name: sa-token

    secret:
      secretName: api-reader-token