apiVersion: v1
kind: ServiceAccount

metadata:
  name: pod-reader-sa
  namespace: default

---
# RBAC，创建一个角色并定义这个角色的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: pod-reader-role
  # 能够在default命名空间下读取pod资源
  namespace: default

rules:
- apiGroups:
  - ""

  resources:
  # 允许操作pod资源
  - pods

  verbs:
  - get
  - list
  - watch


---
# pod-reader-sa

# 绑定

# pod-reader-role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: pod-reader-binding
  namespace: default


subjects:

- kind: ServiceAccount
  name: pod-reader-sa
  # 指定serviceAccount所在的命名空间
  namespace: default


roleRef:

  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod

metadata:
  name: api-test


spec:

  serviceAccountName: pod-reader-sa
  containers:

  - name: test

    image: nginx:1.27.3

    command:
    - sleep
    - "3600"