package codegen.test.dao.mbg;

import codegen.test.domain.pojo.Menu;
import codegen.test.domain.query.example.MenuExample;
import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    long countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    List<Menu> selectByExampleWithRowbounds(MenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    List<Menu> selectByExampleDeepPagingByIdSubQuery(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Aug 14 23:37:24 CST 2025
     */
    int insertBatch(Collection<Menu> records);
}