server:
  port: 80
logging:
  level:
    mybatis: DEBUG
spring:
  jdbc:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java_web
        username: root
        password: root