# 当service使用了target-port-name的时候，并且指向不同port的时候，endpointslice的行为
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/appname: nginx-app
  ports:
    - protocol: TCP
      port: 80
      # 将
      targetPort: http-web-svc
---
# 这是个开放了80端口的nginx，端口命名为http-web-svc
apiVersion: v1
kind: Pod
metadata:
  name: my-app-1
  labels:
    app.kubernetes.io/appname: nginx-app
spec:
  containers:
    - name: nginx
      image: goose-good/nginx:1.27.3
      ports:
        - containerPort: 80
          name: http-web-svc
---
# 这是个开放了8080端口的nginx，端口命名为http-web-svc
apiVersion: v1
kind: Pod
metadata:
  name: my-app-2
  labels:
    app.kubernetes.io/appname: nginx-app
spec:
  containers:
    - name: nginx
      image: goose-good/nginx:1.27.3
      ports:
        - containerPort: 8080 # 容器内端口改为 8080
          name: http-web-svc
      command: ["/bin/sh", "-c"]
      args:
        - |
          # 修改默认端口配置
          sed -i 's/listen \+80/listen 8080/g' /etc/nginx/conf.d/default.conf
          # 启动 Nginx
          exec nginx -g 'daemon off;'
