apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    release: stable
    environment: dev
spec:
  capacity:
    storage: 5Gi
  # 本机测试，只能用local的方式来测试
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # 官网说不建议使用hostPath，要使用local
  # hostPath:
  #   path: "/home/dominiczhu/Coding/talk-is-cheap/container/kubernetes/tutorials/concept/storage/persistent-volumes/fake-ssd"
  # 这需要是一个合法的域名，如果不合法会正则校验报错
  storageClassName: local-path
  local:
    path: /mnt/data
  # 节点亲和性，我当前使用的是minikube，可以kubectl describe node/minikube看到当前节点的labels里刚好有一个标签：kubernetes.io/hostname=minikube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0001-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
  # 要么直接指定volumeName，要么通过selector来筛选
  # volumeName: pv0001
  selector:
    matchLabels:
      release: stable
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pv0001-claim
  containers:
    - name: task-pv-container
      image: goose-good/busybox:1.37.0
      command: 
        - sh
        - -c
        - | 
          echo "The app is running!" && 
          ls -l /mnt/pv0001 && 
          cat /mnt/pv0001/* &&
          echo ""
      volumeMounts:
        - mountPath: "/mnt/pv0001"
          name: task-pv-storage