package org.talk.is.cheap.project.what.to.eat.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商户的营销计划
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table business_marketing_plan
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class BusinessMarketingPlan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.business_id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Long businessId;

    /**
     * Database Column Remarks:
     *   活动开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.marketing_start_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Date marketingStartTime;

    /**
     * Database Column Remarks:
     *   活动结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.marketing_end_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Date marketingEndTime;

    /**
     * Database Column Remarks:
     *   商户活动cron表达式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.cron
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private String cron;

    /**
     * Database Column Remarks:
     *   活动标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.marketing_title
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private String marketingTitle;

    /**
     * Database Column Remarks:
     *   活动详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.marketing_detail
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private String marketingDetail;

    /**
     * Database Column Remarks:
     *   活动状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.status
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.revision
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.create_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_marketing_plan.update_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    private static final long serialVersionUID = 1L;

    public static final String ID = "id";

    public static final String BUSINESS_ID = "business_id";

    public static final String MARKETING_START_TIME = "marketing_start_time";

    public static final String MARKETING_END_TIME = "marketing_end_time";

    public static final String CRON = "cron";

    public static final String MARKETING_TITLE = "marketing_title";

    public static final String MARKETING_DETAIL = "marketing_detail";

    public static final String STATUS = "status";

    public static final String REVISION = "revision";

    public static final String CREATE_TIME = "create_time";

    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.id
     *
     * @return the value of business_marketing_plan.id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.id
     *
     * @param id the value for business_marketing_plan.id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.business_id
     *
     * @return the value of business_marketing_plan.business_id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withBusinessId(Long businessId) {
        this.setBusinessId(businessId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.business_id
     *
     * @param businessId the value for business_marketing_plan.business_id
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.marketing_start_time
     *
     * @return the value of business_marketing_plan.marketing_start_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Date getMarketingStartTime() {
        return marketingStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withMarketingStartTime(Date marketingStartTime) {
        this.setMarketingStartTime(marketingStartTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.marketing_start_time
     *
     * @param marketingStartTime the value for business_marketing_plan.marketing_start_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setMarketingStartTime(Date marketingStartTime) {
        this.marketingStartTime = marketingStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.marketing_end_time
     *
     * @return the value of business_marketing_plan.marketing_end_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Date getMarketingEndTime() {
        return marketingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withMarketingEndTime(Date marketingEndTime) {
        this.setMarketingEndTime(marketingEndTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.marketing_end_time
     *
     * @param marketingEndTime the value for business_marketing_plan.marketing_end_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setMarketingEndTime(Date marketingEndTime) {
        this.marketingEndTime = marketingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.cron
     *
     * @return the value of business_marketing_plan.cron
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withCron(String cron) {
        this.setCron(cron);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.cron
     *
     * @param cron the value for business_marketing_plan.cron
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.marketing_title
     *
     * @return the value of business_marketing_plan.marketing_title
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public String getMarketingTitle() {
        return marketingTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withMarketingTitle(String marketingTitle) {
        this.setMarketingTitle(marketingTitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.marketing_title
     *
     * @param marketingTitle the value for business_marketing_plan.marketing_title
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setMarketingTitle(String marketingTitle) {
        this.marketingTitle = marketingTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.marketing_detail
     *
     * @return the value of business_marketing_plan.marketing_detail
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public String getMarketingDetail() {
        return marketingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withMarketingDetail(String marketingDetail) {
        this.setMarketingDetail(marketingDetail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.marketing_detail
     *
     * @param marketingDetail the value for business_marketing_plan.marketing_detail
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setMarketingDetail(String marketingDetail) {
        this.marketingDetail = marketingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.status
     *
     * @return the value of business_marketing_plan.status
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.status
     *
     * @param status the value for business_marketing_plan.status
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.revision
     *
     * @return the value of business_marketing_plan.revision
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.revision
     *
     * @param revision the value for business_marketing_plan.revision
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.create_time
     *
     * @return the value of business_marketing_plan.create_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.create_time
     *
     * @param createTime the value for business_marketing_plan.create_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_marketing_plan.update_time
     *
     * @return the value of business_marketing_plan.update_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public BusinessMarketingPlan withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_marketing_plan.update_time
     *
     * @param updateTime the value for business_marketing_plan.update_time
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", businessId=").append(businessId);
        sb.append(", marketingStartTime=").append(marketingStartTime);
        sb.append(", marketingEndTime=").append(marketingEndTime);
        sb.append(", cron=").append(cron);
        sb.append(", marketingTitle=").append(marketingTitle);
        sb.append(", marketingDetail=").append(marketingDetail);
        sb.append(", status=").append(status);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BusinessMarketingPlan other = (BusinessMarketingPlan) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getMarketingStartTime() == null ? other.getMarketingStartTime() == null : this.getMarketingStartTime().equals(other.getMarketingStartTime()))
            && (this.getMarketingEndTime() == null ? other.getMarketingEndTime() == null : this.getMarketingEndTime().equals(other.getMarketingEndTime()))
            && (this.getCron() == null ? other.getCron() == null : this.getCron().equals(other.getCron()))
            && (this.getMarketingTitle() == null ? other.getMarketingTitle() == null : this.getMarketingTitle().equals(other.getMarketingTitle()))
            && (this.getMarketingDetail() == null ? other.getMarketingDetail() == null : this.getMarketingDetail().equals(other.getMarketingDetail()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Thu Nov 23 22:53:11 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getMarketingStartTime() == null) ? 0 : getMarketingStartTime().hashCode());
        result = prime * result + ((getMarketingEndTime() == null) ? 0 : getMarketingEndTime().hashCode());
        result = prime * result + ((getCron() == null) ? 0 : getCron().hashCode());
        result = prime * result + ((getMarketingTitle() == null) ? 0 : getMarketingTitle().hashCode());
        result = prime * result + ((getMarketingDetail() == null) ? 0 : getMarketingDetail().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}