# 另一个namespace的service
apiVersion: v1
kind: Namespace
metadata:
  name: other-ns  # 命名空间名称
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: other-ns
  labels:
    app.kubernetes.io/lname: my-app
spec:
  containers:
  - name: nginx
    image: goose-good/nginx:1.27.3
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-in-other-ns
  namespace: other-ns
spec:
  selector:
    app.kubernetes.io/lname: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80