# 使用官方 Nginx 基础镜像
FROM nginx:1.27.3

# 删除默认配置
# RUN  mkdir /etc/nginx/ssl
RUN rm /etc/nginx/conf.d/default.conf && mkdir /etc/nginx/ssl

# 复制自定义配置文件，conf.d文件里的配置信息会被引入到/etc/nginx/nginx.conf之中后生效。
COPY nginx-server.conf /etc/nginx/conf.d/

# 复制 SSL 证书和密钥
COPY certs/server_certificate.pem /etc/nginx/ssl/
COPY certs/server_private_key.pem /etc/nginx/ssl/

# 暴露 80 和 443 端口
EXPOSE 80 443

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]