package com.example.springboot.hellospringboot.dao.mbg;

import com.example.springboot.hellospringboot.domain.pojo.Customers;
import com.example.springboot.hellospringboot.domain.query.example.CustomersExample;
import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    long countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int deleteByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int deleteByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    List<Customers> selectByExampleWithRowbounds(CustomersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    Customers selectByPrimaryKey(Integer customernumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int updateByExampleSelective(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int updateByExample(@Param("record") Customers record, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int updateByPrimaryKey(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:40:37 CST 2022
     */
    int insertBatch(Collection<Customers> records);
}