package org.talk.is.cheap.project.free.flow.scheduler.cluster.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   集群节点登入登出日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cluster_node_registry_log
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class ClusterNodeRegistryLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   节点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.node_id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private String nodeId;

    /**
     * Database Column Remarks:
     *   节点类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.node_type
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Integer nodeType;

    /**
     * Database Column Remarks:
     *   节点行为
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.node_action
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Integer nodeAction;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.revision
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.create_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_node_registry_log.update_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String NODE_ID = "node_id";

    /**
    used in order-by
    */
    public static final String NODE_TYPE = "node_type";

    /**
    used in order-by
    */
    public static final String NODE_ACTION = "node_action";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.id
     *
     * @return the value of cluster_node_registry_log.id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.id
     *
     * @param id the value for cluster_node_registry_log.id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.node_id
     *
     * @return the value of cluster_node_registry_log.node_id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withNodeId(String nodeId) {
        this.setNodeId(nodeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.node_id
     *
     * @param nodeId the value for cluster_node_registry_log.node_id
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.node_type
     *
     * @return the value of cluster_node_registry_log.node_type
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withNodeType(Integer nodeType) {
        this.setNodeType(nodeType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.node_type
     *
     * @param nodeType the value for cluster_node_registry_log.node_type
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.node_action
     *
     * @return the value of cluster_node_registry_log.node_action
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Integer getNodeAction() {
        return nodeAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withNodeAction(Integer nodeAction) {
        this.setNodeAction(nodeAction);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.node_action
     *
     * @param nodeAction the value for cluster_node_registry_log.node_action
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setNodeAction(Integer nodeAction) {
        this.nodeAction = nodeAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.revision
     *
     * @return the value of cluster_node_registry_log.revision
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.revision
     *
     * @param revision the value for cluster_node_registry_log.revision
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.create_time
     *
     * @return the value of cluster_node_registry_log.create_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.create_time
     *
     * @param createTime the value for cluster_node_registry_log.create_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_node_registry_log.update_time
     *
     * @return the value of cluster_node_registry_log.update_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public ClusterNodeRegistryLog withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_node_registry_log.update_time
     *
     * @param updateTime the value for cluster_node_registry_log.update_time
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", nodeType=").append(nodeType);
        sb.append(", nodeAction=").append(nodeAction);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClusterNodeRegistryLog other = (ClusterNodeRegistryLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
            && (this.getNodeType() == null ? other.getNodeType() == null : this.getNodeType().equals(other.getNodeType()))
            && (this.getNodeAction() == null ? other.getNodeAction() == null : this.getNodeAction().equals(other.getNodeAction()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_registry_log
     *
     * @mbg.generated Wed Jul 30 22:19:26 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
        result = prime * result + ((getNodeType() == null) ? 0 : getNodeType().hashCode());
        result = prime * result + ((getNodeAction() == null) ? 0 : getNodeAction().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}