package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   阶段执行主表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table stage_execution
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class StageExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   阶段启动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.stage_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long stageStartupId;

    /**
     * Database Column Remarks:
     *   执行此次阶段的worker的地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.worker_address
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private String workerAddress;

    /**
     * Database Column Remarks:
     *   此次执行的状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   阶段启动时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String STAGE_STARTUP_ID = "stage_startup_id";

    /**
    used in order-by
    */
    public static final String WORKER_ADDRESS = "worker_address";

    /**
    used in order-by
    */
    public static final String STATUS = "status";

    /**
    used in order-by
    */
    public static final String START_TIME = "start_time";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.id
     *
     * @return the value of stage_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.id
     *
     * @param id the value for stage_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.stage_startup_id
     *
     * @return the value of stage_execution.stage_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getStageStartupId() {
        return stageStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withStageStartupId(Long stageStartupId) {
        this.setStageStartupId(stageStartupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.stage_startup_id
     *
     * @param stageStartupId the value for stage_execution.stage_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setStageStartupId(Long stageStartupId) {
        this.stageStartupId = stageStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.worker_address
     *
     * @return the value of stage_execution.worker_address
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public String getWorkerAddress() {
        return workerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withWorkerAddress(String workerAddress) {
        this.setWorkerAddress(workerAddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.worker_address
     *
     * @param workerAddress the value for stage_execution.worker_address
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setWorkerAddress(String workerAddress) {
        this.workerAddress = workerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.status
     *
     * @return the value of stage_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.status
     *
     * @param status the value for stage_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.start_time
     *
     * @return the value of stage_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withStartTime(Date startTime) {
        this.setStartTime(startTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.start_time
     *
     * @param startTime the value for stage_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.revision
     *
     * @return the value of stage_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.revision
     *
     * @param revision the value for stage_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.create_time
     *
     * @return the value of stage_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.create_time
     *
     * @param createTime the value for stage_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_execution.update_time
     *
     * @return the value of stage_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public StageExecution withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_execution.update_time
     *
     * @param updateTime the value for stage_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stageStartupId=").append(stageStartupId);
        sb.append(", workerAddress=").append(workerAddress);
        sb.append(", status=").append(status);
        sb.append(", startTime=").append(startTime);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StageExecution other = (StageExecution) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStageStartupId() == null ? other.getStageStartupId() == null : this.getStageStartupId().equals(other.getStageStartupId()))
            && (this.getWorkerAddress() == null ? other.getWorkerAddress() == null : this.getWorkerAddress().equals(other.getWorkerAddress()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStageStartupId() == null) ? 0 : getStageStartupId().hashCode());
        result = prime * result + ((getWorkerAddress() == null) ? 0 : getWorkerAddress().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}