package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   任务图结构定义表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_graph_definition
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class TaskGraphDefinition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.task_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long taskId;

    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.from_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long fromStageId;

    /**
     * Database Column Remarks:
     *   阶段名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.to_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Long toStageId;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_graph_definition.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String TASK_ID = "task_id";

    /**
    used in order-by
    */
    public static final String FROM_STAGE_ID = "from_stage_id";

    /**
    used in order-by
    */
    public static final String TO_STAGE_ID = "to_stage_id";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.id
     *
     * @return the value of task_graph_definition.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.id
     *
     * @param id the value for task_graph_definition.id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.task_id
     *
     * @return the value of task_graph_definition.task_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withTaskId(Long taskId) {
        this.setTaskId(taskId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.task_id
     *
     * @param taskId the value for task_graph_definition.task_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.from_stage_id
     *
     * @return the value of task_graph_definition.from_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getFromStageId() {
        return fromStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withFromStageId(Long fromStageId) {
        this.setFromStageId(fromStageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.from_stage_id
     *
     * @param fromStageId the value for task_graph_definition.from_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setFromStageId(Long fromStageId) {
        this.fromStageId = fromStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.to_stage_id
     *
     * @return the value of task_graph_definition.to_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Long getToStageId() {
        return toStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withToStageId(Long toStageId) {
        this.setToStageId(toStageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.to_stage_id
     *
     * @param toStageId the value for task_graph_definition.to_stage_id
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setToStageId(Long toStageId) {
        this.toStageId = toStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.create_time
     *
     * @return the value of task_graph_definition.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.create_time
     *
     * @param createTime the value for task_graph_definition.create_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_graph_definition.update_time
     *
     * @return the value of task_graph_definition.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public TaskGraphDefinition withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_graph_definition.update_time
     *
     * @param updateTime the value for task_graph_definition.update_time
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", fromStageId=").append(fromStageId);
        sb.append(", toStageId=").append(toStageId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskGraphDefinition other = (TaskGraphDefinition) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getFromStageId() == null ? other.getFromStageId() == null : this.getFromStageId().equals(other.getFromStageId()))
            && (this.getToStageId() == null ? other.getToStageId() == null : this.getToStageId().equals(other.getToStageId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getFromStageId() == null) ? 0 : getFromStageId().hashCode());
        result = prime * result + ((getToStageId() == null) ? 0 : getToStageId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}