package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   任务启动来源关系表，一个任务的启动可能是被重新调度而生成的，该表用于记录启动一个task的原因
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_source_target_startup_relation
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class TaskSourceTargetStartupRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用于描述此次task启动的原因的类型，例如作为初始stage、循环触发、前一个stage完成等等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.source_type
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Integer sourceType;

    /**
     * Database Column Remarks:
     *   用于描述此次task启动的原因的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.source_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Long sourceId;

    /**
     * Database Column Remarks:
     *   stage启动的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.target_task_startup_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Long targetTaskStartupId;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.revision
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.create_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_source_target_startup_relation.update_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String SOURCE_TYPE = "source_type";

    /**
    used in order-by
    */
    public static final String SOURCE_ID = "source_id";

    /**
    used in order-by
    */
    public static final String TARGET_TASK_STARTUP_ID = "target_task_startup_id";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.id
     *
     * @return the value of task_source_target_startup_relation.id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.id
     *
     * @param id the value for task_source_target_startup_relation.id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.source_type
     *
     * @return the value of task_source_target_startup_relation.source_type
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withSourceType(Integer sourceType) {
        this.setSourceType(sourceType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.source_type
     *
     * @param sourceType the value for task_source_target_startup_relation.source_type
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.source_id
     *
     * @return the value of task_source_target_startup_relation.source_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withSourceId(Long sourceId) {
        this.setSourceId(sourceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.source_id
     *
     * @param sourceId the value for task_source_target_startup_relation.source_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.target_task_startup_id
     *
     * @return the value of task_source_target_startup_relation.target_task_startup_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Long getTargetTaskStartupId() {
        return targetTaskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withTargetTaskStartupId(Long targetTaskStartupId) {
        this.setTargetTaskStartupId(targetTaskStartupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.target_task_startup_id
     *
     * @param targetTaskStartupId the value for task_source_target_startup_relation.target_task_startup_id
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setTargetTaskStartupId(Long targetTaskStartupId) {
        this.targetTaskStartupId = targetTaskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.revision
     *
     * @return the value of task_source_target_startup_relation.revision
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.revision
     *
     * @param revision the value for task_source_target_startup_relation.revision
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.create_time
     *
     * @return the value of task_source_target_startup_relation.create_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.create_time
     *
     * @param createTime the value for task_source_target_startup_relation.create_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_source_target_startup_relation.update_time
     *
     * @return the value of task_source_target_startup_relation.update_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public TaskSourceTargetStartupRelation withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_source_target_startup_relation.update_time
     *
     * @param updateTime the value for task_source_target_startup_relation.update_time
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", sourceId=").append(sourceId);
        sb.append(", targetTaskStartupId=").append(targetTaskStartupId);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskSourceTargetStartupRelation other = (TaskSourceTargetStartupRelation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSourceType() == null ? other.getSourceType() == null : this.getSourceType().equals(other.getSourceType()))
            && (this.getSourceId() == null ? other.getSourceId() == null : this.getSourceId().equals(other.getSourceId()))
            && (this.getTargetTaskStartupId() == null ? other.getTargetTaskStartupId() == null : this.getTargetTaskStartupId().equals(other.getTargetTaskStartupId()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSourceType() == null) ? 0 : getSourceType().hashCode());
        result = prime * result + ((getSourceId() == null) ? 0 : getSourceId().hashCode());
        result = prime * result + ((getTargetTaskStartupId() == null) ? 0 : getTargetTaskStartupId().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}