package org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   任务执行主表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_execution
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class TaskExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   任务启动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.task_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long taskStartupId;

    /**
     * Database Column Remarks:
     *   任务一开始被指派的节点地址，尽可能保障任务在这个节点执行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.assigned_worker_addr
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private String assignedWorkerAddr;

    /**
     * Database Column Remarks:
     *   此次执行的状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   本次执行的共享上下文在es中的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.encoded_shared_context_es_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private String encodedSharedContextEsId;

    /**
     * Database Column Remarks:
     *   任务启动时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.completion_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date completionTime;

    /**
     * Database Column Remarks:
     *   任务启动时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   并发控制编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Long revision;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String TASK_STARTUP_ID = "task_startup_id";

    /**
    used in order-by
    */
    public static final String ASSIGNED_WORKER_ADDR = "assigned_worker_addr";

    /**
    used in order-by
    */
    public static final String STATUS = "status";

    /**
    used in order-by
    */
    public static final String ENCODED_SHARED_CONTEXT_ES_ID = "encoded_shared_context_es_id";

    /**
    used in order-by
    */
    public static final String COMPLETION_TIME = "completion_time";

    /**
    used in order-by
    */
    public static final String START_TIME = "start_time";

    /**
    used in order-by
    */
    public static final String REVISION = "revision";

    /**
    used in order-by
    */
    public static final String CREATE_TIME = "create_time";

    /**
    used in order-by
    */
    public static final String UPDATE_TIME = "update_time";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.id
     *
     * @return the value of task_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.id
     *
     * @param id the value for task_execution.id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.task_startup_id
     *
     * @return the value of task_execution.task_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getTaskStartupId() {
        return taskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withTaskStartupId(Long taskStartupId) {
        this.setTaskStartupId(taskStartupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.task_startup_id
     *
     * @param taskStartupId the value for task_execution.task_startup_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setTaskStartupId(Long taskStartupId) {
        this.taskStartupId = taskStartupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.assigned_worker_addr
     *
     * @return the value of task_execution.assigned_worker_addr
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public String getAssignedWorkerAddr() {
        return assignedWorkerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withAssignedWorkerAddr(String assignedWorkerAddr) {
        this.setAssignedWorkerAddr(assignedWorkerAddr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.assigned_worker_addr
     *
     * @param assignedWorkerAddr the value for task_execution.assigned_worker_addr
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setAssignedWorkerAddr(String assignedWorkerAddr) {
        this.assignedWorkerAddr = assignedWorkerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.status
     *
     * @return the value of task_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.status
     *
     * @param status the value for task_execution.status
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.encoded_shared_context_es_id
     *
     * @return the value of task_execution.encoded_shared_context_es_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public String getEncodedSharedContextEsId() {
        return encodedSharedContextEsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withEncodedSharedContextEsId(String encodedSharedContextEsId) {
        this.setEncodedSharedContextEsId(encodedSharedContextEsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.encoded_shared_context_es_id
     *
     * @param encodedSharedContextEsId the value for task_execution.encoded_shared_context_es_id
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setEncodedSharedContextEsId(String encodedSharedContextEsId) {
        this.encodedSharedContextEsId = encodedSharedContextEsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.completion_time
     *
     * @return the value of task_execution.completion_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getCompletionTime() {
        return completionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withCompletionTime(Date completionTime) {
        this.setCompletionTime(completionTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.completion_time
     *
     * @param completionTime the value for task_execution.completion_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setCompletionTime(Date completionTime) {
        this.completionTime = completionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.start_time
     *
     * @return the value of task_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withStartTime(Date startTime) {
        this.setStartTime(startTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.start_time
     *
     * @param startTime the value for task_execution.start_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.revision
     *
     * @return the value of task_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withRevision(Long revision) {
        this.setRevision(revision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.revision
     *
     * @param revision the value for task_execution.revision
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.create_time
     *
     * @return the value of task_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.create_time
     *
     * @param createTime the value for task_execution.create_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_execution.update_time
     *
     * @return the value of task_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public TaskExecution withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_execution.update_time
     *
     * @param updateTime the value for task_execution.update_time
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskStartupId=").append(taskStartupId);
        sb.append(", assignedWorkerAddr=").append(assignedWorkerAddr);
        sb.append(", status=").append(status);
        sb.append(", encodedSharedContextEsId=").append(encodedSharedContextEsId);
        sb.append(", completionTime=").append(completionTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", revision=").append(revision);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskExecution other = (TaskExecution) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskStartupId() == null ? other.getTaskStartupId() == null : this.getTaskStartupId().equals(other.getTaskStartupId()))
            && (this.getAssignedWorkerAddr() == null ? other.getAssignedWorkerAddr() == null : this.getAssignedWorkerAddr().equals(other.getAssignedWorkerAddr()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getEncodedSharedContextEsId() == null ? other.getEncodedSharedContextEsId() == null : this.getEncodedSharedContextEsId().equals(other.getEncodedSharedContextEsId()))
            && (this.getCompletionTime() == null ? other.getCompletionTime() == null : this.getCompletionTime().equals(other.getCompletionTime()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getRevision() == null ? other.getRevision() == null : this.getRevision().equals(other.getRevision()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Tue Sep 23 20:58:59 CST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskStartupId() == null) ? 0 : getTaskStartupId().hashCode());
        result = prime * result + ((getAssignedWorkerAddr() == null) ? 0 : getAssignedWorkerAddr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getEncodedSharedContextEsId() == null) ? 0 : getEncodedSharedContextEsId().hashCode());
        result = prime * result + ((getCompletionTime() == null) ? 0 : getCompletionTime().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getRevision() == null) ? 0 : getRevision().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}