package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.ClusterNodeExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.ClusterNode;

public interface ClusterNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    long countByExample(ClusterNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    int deleteByExample(ClusterNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    int insertSelective(ClusterNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    List<ClusterNode> selectByExampleWithRowbounds(ClusterNodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    List<ClusterNode> selectByExample(ClusterNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    int updateByExampleSelective(@Param("record") ClusterNode record, @Param("example") ClusterNodeExample example);

    List<ClusterNode> selectByExampleDeepPagingByIdSubQuery(ClusterNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    int insertBatch(Collection<ClusterNode> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node
     *
     * @mbg.generated Tue Jan 06 22:28:51 CST 2026
     */
    int insertBatchSelective(@Param("records") Collection<ClusterNode> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}