package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.ClusterNodeLog;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.ClusterNodeLogExample;

public interface ClusterNodeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    long countByExample(ClusterNodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    int deleteByExample(ClusterNodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    int insertSelective(ClusterNodeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    List<ClusterNodeLog> selectByExampleWithRowbounds(ClusterNodeLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    List<ClusterNodeLog> selectByExample(ClusterNodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") ClusterNodeLog record, @Param("example") ClusterNodeLogExample example);

    List<ClusterNodeLog> selectByExampleDeepPagingByIdSubQuery(ClusterNodeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_node_log
     *
     * @mbg.generated Sun Sep 07 20:30:12 CST 2025
     */
    int insertBatch(Collection<ClusterNodeLog> records);
}