package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.ScheduleTaskDefinitionExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.ScheduleTaskDefinition;

public interface ScheduleTaskDefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    long countByExample(ScheduleTaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int deleteByExample(ScheduleTaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertSelective(ScheduleTaskDefinition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<ScheduleTaskDefinition> selectByExampleWithRowbounds(ScheduleTaskDefinitionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<ScheduleTaskDefinition> selectByExample(ScheduleTaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int updateByExampleSelective(@Param("record") ScheduleTaskDefinition record, @Param("example") ScheduleTaskDefinitionExample example);

    List<ScheduleTaskDefinition> selectByExampleDeepPagingByIdSubQuery(ScheduleTaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatch(Collection<ScheduleTaskDefinition> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatchSelective(@Param("records") Collection<ScheduleTaskDefinition> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}