package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.SeqGenerator;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.SeqGeneratorExample;

public interface SeqGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    long countByExample(SeqGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int deleteByExample(SeqGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int insertSelective(SeqGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    List<SeqGenerator> selectByExampleWithRowbounds(SeqGeneratorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    List<SeqGenerator> selectByExample(SeqGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int updateByExampleSelective(@Param("record") SeqGenerator record, @Param("example") SeqGeneratorExample example);

    List<SeqGenerator> selectByExampleDeepPagingByIdSubQuery(SeqGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seq_generator
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int insertBatch(Collection<SeqGenerator> records);
}