package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.StageStartupExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.StageStartup;

public interface StageStartupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    long countByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    int deleteByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    int insertSelective(StageStartup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    List<StageStartup> selectByExampleWithRowbounds(StageStartupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    List<StageStartup> selectByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    int updateByExampleSelective(@Param("record") StageStartup record, @Param("example") StageStartupExample example);

    List<StageStartup> selectByExampleDeepPagingByIdSubQuery(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    int insertBatch(Collection<StageStartup> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Wed Dec 03 21:19:56 CST 2025
     */
    int insertBatchSelective(@Param("records") Collection<StageStartup> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}