package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.StageDefinitionExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.StageDefinition;

public interface StageDefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    long countByExample(StageDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int deleteByExample(StageDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertSelective(StageDefinition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<StageDefinition> selectByExampleWithRowbounds(StageDefinitionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<StageDefinition> selectByExample(StageDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int updateByExampleSelective(@Param("record") StageDefinition record, @Param("example") StageDefinitionExample example);

    List<StageDefinition> selectByExampleDeepPagingByIdSubQuery(StageDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatch(Collection<StageDefinition> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatchSelective(@Param("records") Collection<StageDefinition> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}