package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.StageExecution;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.StageExecutionExample;

public interface StageExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    long countByExample(StageExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int deleteByExample(StageExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int insertSelective(StageExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    List<StageExecution> selectByExampleWithRowbounds(StageExecutionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    List<StageExecution> selectByExample(StageExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int updateByExampleSelective(@Param("record") StageExecution record, @Param("example") StageExecutionExample example);

    List<StageExecution> selectByExampleDeepPagingByIdSubQuery(StageExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_execution
     *
     * @mbg.generated Sat Aug 16 10:13:53 CST 2025
     */
    int insertBatch(Collection<StageExecution> records);
}