package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.TaskSourceTargetStartupRelationExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskSourceTargetStartupRelation;

public interface TaskSourceTargetStartupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    long countByExample(TaskSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    int deleteByExample(TaskSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    int insertSelective(TaskSourceTargetStartupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    List<TaskSourceTargetStartupRelation> selectByExampleWithRowbounds(TaskSourceTargetStartupRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    List<TaskSourceTargetStartupRelation> selectByExample(TaskSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    int updateByExampleSelective(@Param("record") TaskSourceTargetStartupRelation record, @Param("example") TaskSourceTargetStartupRelationExample example);

    List<TaskSourceTargetStartupRelation> selectByExampleDeepPagingByIdSubQuery(TaskSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    int insertBatch(Collection<TaskSourceTargetStartupRelation> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_source_target_startup_relation
     *
     * @mbg.generated Fri Feb 27 22:08:28 CST 2026
     */
    int insertBatchSelective(@Param("records") Collection<TaskSourceTargetStartupRelation> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}