package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg.query.example.TaskDefinitionExample;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskDefinition;

public interface TaskDefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    long countByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int deleteByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertSelective(TaskDefinition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<TaskDefinition> selectByExampleWithRowbounds(TaskDefinitionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    List<TaskDefinition> selectByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int updateByExampleSelective(@Param("record") TaskDefinition record, @Param("example") TaskDefinitionExample example);

    List<TaskDefinition> selectByExampleDeepPagingByIdSubQuery(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatch(Collection<TaskDefinition> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Mon Sep 22 21:49:41 CST 2025
     */
    int insertBatchSelective(@Param("records") Collection<TaskDefinition> records, @Param("excludeColNames") HashSet<String> excludeColNames);
}