# HTTPS 证书配置（内网建议开启）
# tls_server_config:
#   cert_file: "/etc/prometheus/cert/server.crt"
#   key_file: "/etc/prometheus/cert/server.key"

# 配置基础账号（两个账号）
basic_auth_users:
  # 管理员账号：完整权限
  admin: "$2y$12$QSX390iiL.oRreIjc0boq.pi.eFS4hADGgcW0zlq3mMn4qWR/.kB."
  # Grafana专用只读账号
  grafana: "$2y$12$psVqEfFGgJ7oM40xEWc6yugqWT4xmKoVzNQh/dwGLfH3AdxJJcO2G"

