apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: goose-good/alpine:3
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: goose-good/alpine:3
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /opt
      # sidecar和主应用容器共享同一个卷，这样sidecar容器就可以访问主应用容器的日志文件
      volumes:
        - name: data
          emptyDir: {}