spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/yiibaidb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 2
      max-wait: 3000
