package codegen.test.domain.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.label
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.route_path
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private String routePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.route_element
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private String routeElement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
    used in order-by
    */
    public static final String ID = "id";

    /**
    used in order-by
    */
    public static final String LABEL = "label";

    /**
    used in order-by
    */
    public static final String PID = "pid";

    /**
    used in order-by
    */
    public static final String ICON = "icon";

    /**
    used in order-by
    */
    public static final String ROUTE_PATH = "route_path";

    /**
    used in order-by
    */
    public static final String ROUTE_ELEMENT = "route_element";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.label
     *
     * @return the value of menu.label
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withLabel(String label) {
        this.setLabel(label);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.label
     *
     * @param label the value for menu.label
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.pid
     *
     * @return the value of menu.pid
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withPid(Integer pid) {
        this.setPid(pid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.pid
     *
     * @param pid the value for menu.pid
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withIcon(String icon) {
        this.setIcon(icon);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.route_path
     *
     * @return the value of menu.route_path
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public String getRoutePath() {
        return routePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withRoutePath(String routePath) {
        this.setRoutePath(routePath);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.route_path
     *
     * @param routePath the value for menu.route_path
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setRoutePath(String routePath) {
        this.routePath = routePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.route_element
     *
     * @return the value of menu.route_element
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public String getRouteElement() {
        return routeElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public Menu withRouteElement(String routeElement) {
        this.setRouteElement(routeElement);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.route_element
     *
     * @param routeElement the value for menu.route_element
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    public void setRouteElement(String routeElement) {
        this.routeElement = routeElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", label=").append(label);
        sb.append(", pid=").append(pid);
        sb.append(", icon=").append(icon);
        sb.append(", routePath=").append(routePath);
        sb.append(", routeElement=").append(routeElement);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Menu other = (Menu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLabel() == null ? other.getLabel() == null : this.getLabel().equals(other.getLabel()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getRoutePath() == null ? other.getRoutePath() == null : this.getRoutePath().equals(other.getRoutePath()))
            && (this.getRouteElement() == null ? other.getRouteElement() == null : this.getRouteElement().equals(other.getRouteElement()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Thu Feb 01 22:35:23 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLabel() == null) ? 0 : getLabel().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getRoutePath() == null) ? 0 : getRoutePath().hashCode());
        result = prime * result + ((getRouteElement() == null) ? 0 : getRouteElement().hashCode());
        return result;
    }

    public static enum PidEnum {
        LOCAL(0,"本地"),
        RUNNING(103,"运行中");

        private final Integer value;

        private final String description;

        private PidEnum(Integer value, String description) {
            this.value = value;
            this.description = description;
        }

        public Integer getValue() {
            return this.value;
        }

        public String getDescription() {
            return this.description;
        }

        public static PidEnum getByValue(Integer value) {
            if (value == null) {
                return null;
            }
            for (PidEnum e : PidEnum.values()) {
                if (e.getValue().equals(value)) {
                    return e;
                }
            }
            return null;
        }
    }
}