apiVersion: v1
kind: Pod
metadata:
  name: configmap-volumes-pod
spec:
  containers:
    - name: configmap-volumes-pod-container
      image: goose-good/busybox:1.37.0
      command: ["sh","-c"]
      args: ["sleep 3600"]
      volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
  - name: foo
    configMap:
      name: game-demo