package org.talk.is.cheap.project.free.flow.scheduler.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.scheduler.repository.domain.pojo.SchedulerLog;
import org.talk.is.cheap.project.free.flow.scheduler.repository.domain.query.example.SchedulerLogExample;

public interface SchedulerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    long countByExample(SchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    int deleteByExample(SchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    int insertSelective(SchedulerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    List<SchedulerLog> selectByExampleWithRowbounds(SchedulerLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    List<SchedulerLog> selectByExample(SchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    int updateByExampleSelective(@Param("record") SchedulerLog record, @Param("example") SchedulerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_log
     *
     * @mbg.generated Tue Aug 12 21:58:36 CST 2025
     */
    int insertBatch(Collection<SchedulerLog> records);
}