package com.example.springboot.hellospringboot.domain.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customers
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class Customers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customerNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private Integer customernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customerName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contactLastName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String contactlastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contactFirstName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String contactfirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.phone
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.addressLine1
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String addressline1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.addressLine2
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String addressline2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.city
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.state
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.postalCode
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.country
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.salesRepEmployeeNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private Integer salesrepemployeenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.creditLimit
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private BigDecimal creditlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customerNumber
     *
     * @return the value of customers.customerNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Integer getCustomernumber() {
        return customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withCustomernumber(Integer customernumber) {
        this.setCustomernumber(customernumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customerNumber
     *
     * @param customernumber the value for customers.customerNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customerName
     *
     * @return the value of customers.customerName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withCustomername(String customername) {
        this.setCustomername(customername);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customerName
     *
     * @param customername the value for customers.customerName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contactLastName
     *
     * @return the value of customers.contactLastName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getContactlastname() {
        return contactlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withContactlastname(String contactlastname) {
        this.setContactlastname(contactlastname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contactLastName
     *
     * @param contactlastname the value for customers.contactLastName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setContactlastname(String contactlastname) {
        this.contactlastname = contactlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contactFirstName
     *
     * @return the value of customers.contactFirstName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getContactfirstname() {
        return contactfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withContactfirstname(String contactfirstname) {
        this.setContactfirstname(contactfirstname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contactFirstName
     *
     * @param contactfirstname the value for customers.contactFirstName
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setContactfirstname(String contactfirstname) {
        this.contactfirstname = contactfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.phone
     *
     * @return the value of customers.phone
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withPhone(String phone) {
        this.setPhone(phone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.phone
     *
     * @param phone the value for customers.phone
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.addressLine1
     *
     * @return the value of customers.addressLine1
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withAddressline1(String addressline1) {
        this.setAddressline1(addressline1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.addressLine1
     *
     * @param addressline1 the value for customers.addressLine1
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.addressLine2
     *
     * @return the value of customers.addressLine2
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withAddressline2(String addressline2) {
        this.setAddressline2(addressline2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.addressLine2
     *
     * @param addressline2 the value for customers.addressLine2
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.city
     *
     * @return the value of customers.city
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withCity(String city) {
        this.setCity(city);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.city
     *
     * @param city the value for customers.city
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.state
     *
     * @return the value of customers.state
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withState(String state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.state
     *
     * @param state the value for customers.state
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.postalCode
     *
     * @return the value of customers.postalCode
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withPostalcode(String postalcode) {
        this.setPostalcode(postalcode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.postalCode
     *
     * @param postalcode the value for customers.postalCode
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.country
     *
     * @return the value of customers.country
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withCountry(String country) {
        this.setCountry(country);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.country
     *
     * @param country the value for customers.country
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.salesRepEmployeeNumber
     *
     * @return the value of customers.salesRepEmployeeNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Integer getSalesrepemployeenumber() {
        return salesrepemployeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withSalesrepemployeenumber(Integer salesrepemployeenumber) {
        this.setSalesrepemployeenumber(salesrepemployeenumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.salesRepEmployeeNumber
     *
     * @param salesrepemployeenumber the value for customers.salesRepEmployeeNumber
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setSalesrepemployeenumber(Integer salesrepemployeenumber) {
        this.salesrepemployeenumber = salesrepemployeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.creditLimit
     *
     * @return the value of customers.creditLimit
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public BigDecimal getCreditlimit() {
        return creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public Customers withCreditlimit(BigDecimal creditlimit) {
        this.setCreditlimit(creditlimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.creditLimit
     *
     * @param creditlimit the value for customers.creditLimit
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    public void setCreditlimit(BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customernumber=").append(customernumber);
        sb.append(", customername=").append(customername);
        sb.append(", contactlastname=").append(contactlastname);
        sb.append(", contactfirstname=").append(contactfirstname);
        sb.append(", phone=").append(phone);
        sb.append(", addressline1=").append(addressline1);
        sb.append(", addressline2=").append(addressline2);
        sb.append(", city=").append(city);
        sb.append(", state=").append(state);
        sb.append(", postalcode=").append(postalcode);
        sb.append(", country=").append(country);
        sb.append(", salesrepemployeenumber=").append(salesrepemployeenumber);
        sb.append(", creditlimit=").append(creditlimit);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customers other = (Customers) that;
        return (this.getCustomernumber() == null ? other.getCustomernumber() == null : this.getCustomernumber().equals(other.getCustomernumber()))
            && (this.getCustomername() == null ? other.getCustomername() == null : this.getCustomername().equals(other.getCustomername()))
            && (this.getContactlastname() == null ? other.getContactlastname() == null : this.getContactlastname().equals(other.getContactlastname()))
            && (this.getContactfirstname() == null ? other.getContactfirstname() == null : this.getContactfirstname().equals(other.getContactfirstname()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getAddressline1() == null ? other.getAddressline1() == null : this.getAddressline1().equals(other.getAddressline1()))
            && (this.getAddressline2() == null ? other.getAddressline2() == null : this.getAddressline2().equals(other.getAddressline2()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getSalesrepemployeenumber() == null ? other.getSalesrepemployeenumber() == null : this.getSalesrepemployeenumber().equals(other.getSalesrepemployeenumber()))
            && (this.getCreditlimit() == null ? other.getCreditlimit() == null : this.getCreditlimit().equals(other.getCreditlimit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Fri Jan 14 16:01:54 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustomernumber() == null) ? 0 : getCustomernumber().hashCode());
        result = prime * result + ((getCustomername() == null) ? 0 : getCustomername().hashCode());
        result = prime * result + ((getContactlastname() == null) ? 0 : getContactlastname().hashCode());
        result = prime * result + ((getContactfirstname() == null) ? 0 : getContactfirstname().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getAddressline1() == null) ? 0 : getAddressline1().hashCode());
        result = prime * result + ((getAddressline2() == null) ? 0 : getAddressline2().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getSalesrepemployeenumber() == null) ? 0 : getSalesrepemployeenumber().hashCode());
        result = prime * result + ((getCreditlimit() == null) ? 0 : getCreditlimit().hashCode());
        return result;
    }
}