package org.talk.is.cheap.project.what.to.eat.domain.query.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table business_marketing_plan
 *
 * @mbg.generated Mon Aug 07 22:24:00 CST 2023
 */
/**
 * do not modify. if you want to add or delete some column, please re-run codegen
*/
public class BusinessMarketingPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public BusinessMarketingPlanExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNull() {
            addCriterion("business_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNotNull() {
            addCriterion("business_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdEqualTo(Long value) {
            addCriterion("business_id =", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotEqualTo(Long value) {
            addCriterion("business_id <>", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThan(Long value) {
            addCriterion("business_id >", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("business_id >=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThan(Long value) {
            addCriterion("business_id <", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThanOrEqualTo(Long value) {
            addCriterion("business_id <=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIn(List<Long> values) {
            addCriterion("business_id in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotIn(List<Long> values) {
            addCriterion("business_id not in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdBetween(Long value1, Long value2) {
            addCriterion("business_id between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotBetween(Long value1, Long value2) {
            addCriterion("business_id not between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeIsNull() {
            addCriterion("marketing_start_time is null");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeIsNotNull() {
            addCriterion("marketing_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeEqualTo(Date value) {
            addCriterion("marketing_start_time =", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeNotEqualTo(Date value) {
            addCriterion("marketing_start_time <>", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeGreaterThan(Date value) {
            addCriterion("marketing_start_time >", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("marketing_start_time >=", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeLessThan(Date value) {
            addCriterion("marketing_start_time <", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("marketing_start_time <=", value, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeIn(List<Date> values) {
            addCriterion("marketing_start_time in", values, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeNotIn(List<Date> values) {
            addCriterion("marketing_start_time not in", values, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeBetween(Date value1, Date value2) {
            addCriterion("marketing_start_time between", value1, value2, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("marketing_start_time not between", value1, value2, "marketingStartTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeIsNull() {
            addCriterion("marketing_end_time is null");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeIsNotNull() {
            addCriterion("marketing_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeEqualTo(Date value) {
            addCriterion("marketing_end_time =", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeNotEqualTo(Date value) {
            addCriterion("marketing_end_time <>", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeGreaterThan(Date value) {
            addCriterion("marketing_end_time >", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("marketing_end_time >=", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeLessThan(Date value) {
            addCriterion("marketing_end_time <", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("marketing_end_time <=", value, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeIn(List<Date> values) {
            addCriterion("marketing_end_time in", values, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeNotIn(List<Date> values) {
            addCriterion("marketing_end_time not in", values, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeBetween(Date value1, Date value2) {
            addCriterion("marketing_end_time between", value1, value2, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andMarketingEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("marketing_end_time not between", value1, value2, "marketingEndTime");
            return (Criteria) this;
        }

        public Criteria andCronIsNull() {
            addCriterion("cron is null");
            return (Criteria) this;
        }

        public Criteria andCronIsNotNull() {
            addCriterion("cron is not null");
            return (Criteria) this;
        }

        public Criteria andCronEqualTo(String value) {
            addCriterion("cron =", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotEqualTo(String value) {
            addCriterion("cron <>", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronGreaterThan(String value) {
            addCriterion("cron >", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronGreaterThanOrEqualTo(String value) {
            addCriterion("cron >=", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLessThan(String value) {
            addCriterion("cron <", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLessThanOrEqualTo(String value) {
            addCriterion("cron <=", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLike(String value) {
            addCriterion("cron like", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotLike(String value) {
            addCriterion("cron not like", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronIn(List<String> values) {
            addCriterion("cron in", values, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotIn(List<String> values) {
            addCriterion("cron not in", values, "cron");
            return (Criteria) this;
        }

        public Criteria andCronBetween(String value1, String value2) {
            addCriterion("cron between", value1, value2, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotBetween(String value1, String value2) {
            addCriterion("cron not between", value1, value2, "cron");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleIsNull() {
            addCriterion("marketing_title is null");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleIsNotNull() {
            addCriterion("marketing_title is not null");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleEqualTo(String value) {
            addCriterion("marketing_title =", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleNotEqualTo(String value) {
            addCriterion("marketing_title <>", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleGreaterThan(String value) {
            addCriterion("marketing_title >", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleGreaterThanOrEqualTo(String value) {
            addCriterion("marketing_title >=", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleLessThan(String value) {
            addCriterion("marketing_title <", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleLessThanOrEqualTo(String value) {
            addCriterion("marketing_title <=", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleLike(String value) {
            addCriterion("marketing_title like", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleNotLike(String value) {
            addCriterion("marketing_title not like", value, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleIn(List<String> values) {
            addCriterion("marketing_title in", values, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleNotIn(List<String> values) {
            addCriterion("marketing_title not in", values, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleBetween(String value1, String value2) {
            addCriterion("marketing_title between", value1, value2, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingTitleNotBetween(String value1, String value2) {
            addCriterion("marketing_title not between", value1, value2, "marketingTitle");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailIsNull() {
            addCriterion("marketing_detail is null");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailIsNotNull() {
            addCriterion("marketing_detail is not null");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailEqualTo(String value) {
            addCriterion("marketing_detail =", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailNotEqualTo(String value) {
            addCriterion("marketing_detail <>", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailGreaterThan(String value) {
            addCriterion("marketing_detail >", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailGreaterThanOrEqualTo(String value) {
            addCriterion("marketing_detail >=", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailLessThan(String value) {
            addCriterion("marketing_detail <", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailLessThanOrEqualTo(String value) {
            addCriterion("marketing_detail <=", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailLike(String value) {
            addCriterion("marketing_detail like", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailNotLike(String value) {
            addCriterion("marketing_detail not like", value, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailIn(List<String> values) {
            addCriterion("marketing_detail in", values, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailNotIn(List<String> values) {
            addCriterion("marketing_detail not in", values, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailBetween(String value1, String value2) {
            addCriterion("marketing_detail between", value1, value2, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailNotBetween(String value1, String value2) {
            addCriterion("marketing_detail not between", value1, value2, "marketingDetail");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRevisionIsNull() {
            addCriterion("revision is null");
            return (Criteria) this;
        }

        public Criteria andRevisionIsNotNull() {
            addCriterion("revision is not null");
            return (Criteria) this;
        }

        public Criteria andRevisionEqualTo(Long value) {
            addCriterion("revision =", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotEqualTo(Long value) {
            addCriterion("revision <>", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionGreaterThan(Long value) {
            addCriterion("revision >", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionGreaterThanOrEqualTo(Long value) {
            addCriterion("revision >=", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionLessThan(Long value) {
            addCriterion("revision <", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionLessThanOrEqualTo(Long value) {
            addCriterion("revision <=", value, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionIn(List<Long> values) {
            addCriterion("revision in", values, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotIn(List<Long> values) {
            addCriterion("revision not in", values, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionBetween(Long value1, Long value2) {
            addCriterion("revision between", value1, value2, "revision");
            return (Criteria) this;
        }

        public Criteria andRevisionNotBetween(Long value1, Long value2) {
            addCriterion("revision not between", value1, value2, "revision");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_marketing_plan
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 07 22:24:00 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business_marketing_plan
     *
     * @mbg.generated Mon Aug 07 22:24:00 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}