apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: hahahahaha
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi