apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: standard-pvc
  containers:
    - name: pod-with-pv-container
      image: goose-good/busybox:1.37.0
      command: 
        - sh
        - -c
        - | 
          echo "The app is running!"
          ls -l /mnt/pv 
          echo ""
      volumeMounts:
        - mountPath: "/mnt/pv"
          name: pv-storage