package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.StageStartup;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.StageStartupExample;

public interface StageStartupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    long countByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int deleteByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertSelective(StageStartup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<StageStartup> selectByExampleWithRowbounds(StageStartupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<StageStartup> selectByExample(StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int updateByExampleSelective(@Param("record") StageStartup record, @Param("example") StageStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_startup
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertBatch(Collection<StageStartup> records);
}