package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.StageSourceTargetStartupRelation;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.StageSourceTargetStartupRelationExample;

public interface StageSourceTargetStartupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    long countByExample(StageSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int deleteByExample(StageSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertSelective(StageSourceTargetStartupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<StageSourceTargetStartupRelation> selectByExampleWithRowbounds(StageSourceTargetStartupRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<StageSourceTargetStartupRelation> selectByExample(StageSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int updateByExampleSelective(@Param("record") StageSourceTargetStartupRelation record, @Param("example") StageSourceTargetStartupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_source_target_startup_relation
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertBatch(Collection<StageSourceTargetStartupRelation> records);
}