package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskExecution;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.TaskExecutionExample;

public interface TaskExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    long countByExample(TaskExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    int deleteByExample(TaskExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    int insertSelective(TaskExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    List<TaskExecution> selectByExampleWithRowbounds(TaskExecutionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    List<TaskExecution> selectByExample(TaskExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    int updateByExampleSelective(@Param("record") TaskExecution record, @Param("example") TaskExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_execution
     *
     * @mbg.generated Wed Aug 13 23:13:19 CST 2025
     */
    int insertBatch(Collection<TaskExecution> records);
}