package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskStartup;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.TaskStartupExample;

public interface TaskStartupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    long countByExample(TaskStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int deleteByExample(TaskStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int insertSelective(TaskStartup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    List<TaskStartup> selectByExampleWithRowbounds(TaskStartupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    List<TaskStartup> selectByExample(TaskStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int updateByExampleSelective(@Param("record") TaskStartup record, @Param("example") TaskStartupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_startup
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int insertBatch(Collection<TaskStartup> records);
}