package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskGraphDefinition;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.TaskGraphDefinitionExample;

public interface TaskGraphDefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    long countByExample(TaskGraphDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int deleteByExample(TaskGraphDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int insertSelective(TaskGraphDefinition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    List<TaskGraphDefinition> selectByExampleWithRowbounds(TaskGraphDefinitionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    List<TaskGraphDefinition> selectByExample(TaskGraphDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int updateByExampleSelective(@Param("record") TaskGraphDefinition record, @Param("example") TaskGraphDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_graph_definition
     *
     * @mbg.generated Wed Aug 13 23:13:18 CST 2025
     */
    int insertBatch(Collection<TaskGraphDefinition> records);
}