package org.talk.is.cheap.project.free.flow.starter.repository.dao.mbg;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.pojo.TaskDefinition;
import org.talk.is.cheap.project.free.flow.starter.repository.domain.query.example.TaskDefinitionExample;

public interface TaskDefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    long countByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int deleteByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertSelective(TaskDefinition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<TaskDefinition> selectByExampleWithRowbounds(TaskDefinitionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    List<TaskDefinition> selectByExample(TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int updateByExampleSelective(@Param("record") TaskDefinition record, @Param("example") TaskDefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_definition
     *
     * @mbg.generated Tue Aug 12 22:32:52 CST 2025
     */
    int insertBatch(Collection<TaskDefinition> records);
}